repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.0
  hooks:
    - id: ruff
- repo: local
  hooks:
    - id: pytest-check
      name: pytest-check
      entry: uv run python3 -m pytest -v .
      language: system
      pass_filenames: false
      always_run: true
