"""add players images

Revision ID: 7e7f6f73932e
Revises: 6c09db951458
Create Date: 2025-04-09 22:13:04.258741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e7f6f73932e'
down_revision: Union[str, None] = '6c09db951458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('avatar_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'avatar_path')
    # ### end Alembic commands ###
