"""add best move

Revision ID: 6c09db951458
Revises: 62920b5dad9d
Create Date: 2025-02-03 15:46:07.876419

"""
from typing import Sequence, Union
from sqlalchemy.sql import false

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c09db951458'
down_revision: Union[str, None] = '62920b5dad9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'players_games',
        sa.Column('in_best_move', sa.Boolean(), nullable=False, server_default=false())
    )
    op.add_column(
        'players_games',
        sa.Column('is_first_killed', sa.Boolean(), nullable=False, server_default=false())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players_games', 'is_first_killed')
    op.drop_column('players_games', 'in_best_move')
    # ### end Alembic commands ###
