name: Example
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - master

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run lint
        run: uv run ruff check

      - name: Build tests
        run: docker compose -f docker-compose-test.yml build

      - name: Run tests
        run: docker compose -f docker-compose-test.yml up --exit-code-from tests

      - name: Stop and remove test containers
        run: docker-compose -f docker-compose-test.yml down
